version: '3.8'

services:
  cashper-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cashper-app
    restart: unless-stopped
    ports:
      - "3000:80"
    env_file:
      - ./cashper_backend/.env
    volumes:
      - ./cashper_backend/uploads:/app/backend/uploads
    networks:
      - cashper-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/api/" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  cashper-network:
    driver: bridge
